# Change the look of Adwaita, with ease
# Copyright (C) 2022 Gradience Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          dnf -y install docker

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: arm64

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          repository-name: gnome-nightly
          bundle: gradience-devel.flatpak
          manifest-path: build-aux/flatpak/com.github.GradienceTeam.Gradience.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
