# Change the look of Adwaita, with ease
# Copyright (C) 2022 Gradience Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

name: Build flatpak nightly
on:
  schedule:
    - cron: '0 23 * * *'
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: com.github.GradienceTeam.Gradience.Devel.flatpak
          manifest-path: build-aux/flatpak/com.github.GradienceTeam.Gradience.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}-nightly
